CircleCI-Public/aws-ecr-orb

src/orb.yml

Hello there @iynere and @eddiewebb,
What do you guys think about adding a parameter **folder** to the **build-image** command?
My use case:
I have a repository with a lot of docker base images separated by folder, and I want to be able to switch folders and build these images.
Thanks!

Add folder parameter to build-image command

---

src/commands/build-and-push-image.yml

Possible resolution of https://github.com/CircleCI-Public/aws-ecr-orb/issues/17.
I don't like the way these parameters are duplicated, which could be difficult to maintain in the future (especially descriptions and defaults).

Expose build-and-push-image as a command

---

src/commands/build-and-push-image.yml

This PR updates the `create-repo` handler to check if the repo exists before creating it.
Resolves #22.
Credit to @peermuellerxw in this comment for the code change: https://github.com/CircleCI-Public/aws-ecr-orb/issues/22#issuecomment-482042615

Fix buggy behaviour of `create-repo` when repo exists

---

src/commands/ecr-login-for-secondary-account.yml

Hi. I'm excited about Orbs!
I tried aws-ecr@4.0.1 and found a missing feature.
The purpose of this PR is to add a secondary account login.
ref: [How can I grant access to a secondary account to pull or push images in my ECR repository?](https://aws.amazon.com/premiumsupport/knowledge-center/secondary-account-access-ecr/)

Support secondary account of Amazon ECR

---

src/commands/build-image.yml

We're presently getting timeouts on our long running angular builds. ~40m.  I tried forking the ORB, but because of this other bug, I cannot at this time publish my own ORBs: https://discuss.circleci.com/t/unable-to-create-namespace-for-my-organization/31426/4 .  The ability to control the timeout should be part of the base orb IMO anyway.
Add the ability to set circle's no_output_timeout setting which can be useful in allowing long running docker constructions.

Increase timeout

---

.circleci/config.yml

Use a new set of IAM credentials for the ecr orb, and provide them via project env variables instead
Use an IAM account customized for the ECR orb instead of the current one in the context.
See CIRCLE-19768.
The project now has the AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION, AWS_ECR_ACCOUNT_URL and AWS_DEFAULT_REGION project environment variables defined and can use the values from them.

[CIRCLE-19768] Remove orb publishing context from integration test job

---

README.md
src/commands/build-and-push-image.yml

Allow the use of the `no-output-timeout` flag on the main command `build-and-push-image`. Without this the only way of increasing the build timeout, is calling the `build-and-push-image` subcommands separately, passing the `no-output-timeout` parameter to the `build-image` command.
A new parameter called `no-output-timeout` is added to the `build-and-push-image` and then passed to the `build-image` command.

Add `no-output-timeout` parameter to `build-and-push-image`

---

src/commands/build-image.yml

PR opened per issue #64 
The `build-image` command now uses the `path` parameter when pointing to a Dockerfile. The same implementation is used in the Docker orb (https://github.com/CircleCI-Public/docker-orb/blob/master/src/commands/build.yml#L107-L119)

Use path parameter for Dockerfile argument

---

src/commands/build-and-push-image.yml
src/commands/ecr-login-for-secondary-account.yml
src/commands/ecr-login.yml

As discussed in the issue below, we added the ability to specify a profile when generating an ecr login URL. 
https://github.com/CircleCI-Public/aws-ecr-orb/issues/9
`aws ecr get-login` can accept the `--profile` flag to specify key and secrets credentials.

ECR get-login with profile [semver:minor]

---

src/jobs/build-and-push-image.yml

There is a typo in the doc regarding env var AWS_ACCESS_KEY_ID
Fix the typo by changing the description.

Fix env var AWS_ACCESS_KEY_ID typo [semver:patch]

---

src/examples/simple-build-and-push.yml
src/jobs/build-and-push-image.yml

#61 added `no-output-timeout` parameter, but `Unexpected argument(s): no-output-timeout` is produced by CircleCI when it's being used.
Cause of this issue is `no-output-timeout` paramter is not passed in `jobs/build-and-push-image.yml`, so it cannot be recognized by CirclecI andproduces error `Unexpected argument(s): no-output-timeout`
Add `no-output-timeout` parameter in `jobs/build-and-push-image.yml` file to fix this issue

Add missing `no-output-timeout` paramter in `jobs/build-and-push-image.yml` [semver:minor]

---

src/@orb.yml
src/commands/build-and-push-image.yml

Pins AWS CLI orb to version 1.2.x, from 0.1.13.

[semver:minor] #103 - Pin AWS CLI orb to version 1.2.x.

---

.circleci/config.yml
Dockerfile
publish-alpha.sh
sample/Dockerfile

Removes the `publish-alpha.sh` script and moves the Dockerfile to the `sample/` directory, as per https://circleci.com/docs/2.0/orbs-best-practices/#sample-data

[semver:skip] Move sample Dockerfile, remove alpha script.

---

.github/stale.yml

adds initial stale.yml file with 60 day policy.
Some issues are months (years!) old and actually invald given platform changes since report.  This will add GitHub's stale bot to mark and eventually close stale issues and PRs unless a user objects and shows continued engagement,

create stale bot rules

---

.circleci/config.yml
README.md
src/commands/build-and-push-image.yml
src/commands/build-image.yml
src/commands/ecr-login.yml
src/examples/simple-build-and-push.yml
src/jobs/build-and-push-image.yml

When using a tagging strategy based on the git commit hash it is unnecessary to spend time rebuilding an image that has been already pushed to the ECR repository. This is particularly relevant when wanting to revert to a previous deployment in production, saving precious time that would have been otherwise spent building the same image that already exists in ECR.
* I've tried my best to keep things backwards compatible, hopefully succeeded at it?
* To avoid repetition I've moved the aws-cli install and configuration into the ecr-login step, as that's when it's needed.

[semver:minor] skip building image when tags already exist in ecr repo

---

src/commands/build-image.yml

- I want to use the `build-image` command directly to make sure the images build on pull requests
- Some of my images are based off other private ECR images, so still need to auth
- Add a `checkout` param to the `build-image` command so we can match the API of `build-and-push-image` (but with default `false` so we don't checkout twice when using the build and push)
- Move all the AWS CLI stuff under the `ecr-login` command so that we can use it in both build and build&push.

[semver:minor] Make 'build-image' command more friendly

---

.circleci/config.yml
src/commands/build-image.yml

This is a PR to fix two issues with my previous PR (https://github.com/CircleCI-Public/aws-ecr-orb/pull/105):
1. The image building was being skipped when *any* tag existed in ECR, as opposed to *all* tags existing, as intended and documented.
2. The docker push command was failing when image building was skipped, as there were no images to push. The existing images are now pulled from ECR so that this push can succeed (it will be very quick as the layers already exist in the remote so nothing will be uploaded).
Added an actual test for the scenario of the image building being skipped when it already exists.
I'm also changing the circleci config to run the integration tests in parallel, for faster feedback

[semver:patch] fix the skip-when-tags-exist condition and fix docker push failure

---

src/commands/ecr-login.yml

Fixes #109
Currently the AWS CLI gets installed twice, this should fix that
In the latest version of the aws-cli orb, the `setup` command includes the install, so we don't need to run that from this orb.
https://github.com/CircleCI-Public/aws-cli-orb/blob/v1.2.1/src/commands/setup.yml#L59

[semver:patch] Remove duplicate 'aws-cli/setup' step

---

README.md
src/commands/build-and-push-image.yml
src/jobs/build-and-push-image.yml

Address feature in GitHub Issue #67 
Enable docker-layer-caching when using remote docker environment
Example:
```
- aws-ecr/build-and-push-image:
aws-access-key-id: AWS_ACCESS_KEY_ID
aws-secret-access-key: AWS_SECRET_ACCESS_KEY
region: AWS_REGION
account-url: ECR_ACCOUNT_URL
repo: << parameters.repo >>
setup-remote-docker: true
remote-docker-layer-caching: true
checkout: false
```

[semver:minor] Option to enable docker layer caching

---

README.md
src/commands/build-and-push-image.yml

To be able run a docker login command as part of the build-and-push-image job.
Example:
- aws-ecr/build-and-push-image:
aws-access-key-id: AWS_ACCESS_KEY_ID
aws-secret-access-key: AWS_SECRET_ACCESS_KEY
region: AWS_REGION
repo: << parameters.repo >>
create-repo: true
docker-login: true

[semver:minor] Setup Dockerhub authentication

---

src/jobs/build-and-push-image.yml

To be able run a docker login command as part of the build-and-push-image job.
Example usage:
- aws-ecr/build-and-push-image:
aws-access-key-id: AWS_ACCESS_KEY_ID
aws-secret-access-key: AWS_SECRET_ACCESS_KEY
region: AWS_REGION
repo: << parameters.repo >>
create-repo: true
docker-login: true
The previous pull request was merged but it didn't solved the problem as i did't updade the actual build-and-push-image job. I just did the update on build-and-push-image command:
https://github.com/CircleCI-Public/aws-ecr-orb/pull/120

[semver:patch] Setup dockerhub authentication (update build-and-push-image job)

---

src/commands/build-and-push-image.yml

Fixing docker login command to be able to get the content of dockerhub-username and dockerhub-password variables.
Currently, the command is not able to do the variables substitution. It's only able to take the default or hardcoded values.

[semver:patch] Fix docker login command

---

src/commands/build-image.yml

Fixes #126 
Adds `--profile` argument to `describe-images` call for `skip-when-tags-exist` so that this command does not fail when using profiles. See #126 for more detail.

[semver:patch] Add profile-name to skip-when-tags-exist describe-images call

---

src/@orb.yml
src/executors/default.yml

We are receiving an error since some days ago by different users (you can check this PR: https://github.com/CircleCI-Public/aws-ecr-orb/issues/136).
I took the idea of upgrading the SO version from this [comment](https://github.com/CircleCI-Public/aws-ecr-orb/issues/134#issuecomment-814066142).
I propose to update the Ubuntu SO version from the 16.04 (`ubuntu-1604:201903-01`) to the 20.04 (`ubuntu-2004:202010-01`) as of this [doc CircleCI reference](https://circleci.com/docs/2.0/configuration-reference/#available-machine-images) mentions.
As I commented [here](https://github.com/CircleCI-Public/aws-ecr-orb/issues/136#issuecomment-814231506), applying directly this change in the `config.yml` file:
```yml
jobs:
build-app:
machine :
image : ubuntu-2004:202010-01
steps:
#...
```
The CI worked …

Update Ubuntu SO version [semver:major]

---

.circleci/config.yml

This PR is for a temporary hot-fix to get the CI pipeline moving so that we may accept current pull requests before further updating the orb.

minimal CI update [semver:skip]

---

.circleci/config.yml

Marking as a minor so previous commit (https://github.com/CircleCI-Public/aws-ecr-orb/commit/2c50edfcd8fcb0a3944a13b7ef9ddf38fa375dd9) is deployed correctly.

[semver:minor] New ssh key for tagging

---

.circleci/test-deploy.yml
sample/policy.json
src/@orb.yml
src/commands/build-and-push-image.yml
src/commands/build-image.yml
src/commands/ecr-login.yml
src/jobs/build-and-push-image.yml
src/scripts/create-repo.sh
src/scripts/docker-buildx.sh
src/scripts/ecr-login.sh
src/scripts/tag-image.sh

**`build-and-push-image`** command was originally removed in `version 8.0` but has been added back by popular demand.
**`build-image`** command now supports adding `aws lifecycle policies` to repositories in `ECR`
- `lifecycle-policy-path`:  The path of the .json file containing the aws lifecycle policy. If a path is defined in this parameter, the policy will be attached to the specified `ECR` repository.
- `assume-web-identity`:  A boolean value that lets the user assume a profile with short lived keys. Set to true to configure a profile using short-term credentials
1. #180 
2. #181 
3. #182
4. #179
5. #188
6. #173 
7. #178  
8. #188 
9. #177 
1.  #184 
2. #183

feat: update v8.1.0

---

src/commands/build-and-push-image.yml
src/scripts/docker-buildx.sh
src/scripts/ecr-login.sh

fix: v8.1.2

---

src/scripts/tag-image.sh

The `target-tag` parameter would not work with an environment variable.
I evaluated the parameter with `PARAM_TARGET_TAG=$(eval echo "${PARAM_TARGET_TAG}")`, enabling the use of environment variables.

fix: expand target-tag parameter with eval

---

.circleci/test-deploy.yml
src/commands/build-and-push-image.yml
src/jobs/build-and-push-image.yml
src/scripts/docker-buildx.sh

This `PR` changes the default value for the `version` parameter in the `setup_remote_docker` command to an empty string.
As of September 6th, if there is no version specified, the `setup_remote_docker` command will use the latest `default` version that's updated on a rolling basis.
More info can be found here: https://discuss.circleci.com/t/default-docker-version-for-remote-docker-jobs-changing-on-september-6/45157/2

fix: changed static default remote docker version

---

src/commands/build-and-push-image.yml

There are two `build-and-push-image` : Command and Job.
The `aws-access-key-id` parameter description has different comments and is inconsistent.
- Command: AWS access key id for IAM role. Set this to the name of the environment variable you will set to hold this value, i.e. AWS_ACCESS_KEY.
- Job: AWS access key id for IAM role. Set this to the name of the environment variable you will set to hold this value, i.e. AWS_ACCESS_KEY_ID.
In this PR, I changed `AWS_ACCESS_KEY` to `AWS_ACCESS_KEY_ID`.
related PR: https://github.com/CircleCI-Public/aws-ecr-orb/pull/96 
I have checked that there is no other part that specifies `AWS_ACCESS_KEY`.

Fix env var AWS_ACCESS_KEY_ID typo

---

src/scripts/docker-buildx.sh

`skip-when-tags-exist` doesn't work in recent versions of the Orb (confirmed with 8.1.2). When an ECR has immutable tags enabled this is a pretty important feature for image builds to flow smoothly.
The issue is that a `contains` query in the CLI command to populate `docker_tag_exists_in_ecr`, outputs `true` or `false` and not `1` or `0`, which the test compares against. Changing this to check for `true` means fixes the issue and correctly increments `number_of_tags_in_ecr` if there is a tag already in ECR which will later skip the build.
fixes #200

fix: skip-when-tags-exist not working

---

src/commands/push-image.yml
src/scripts/push-image.sh

This `PR` adds the `push-image` command to the `aws ecr` orb, enabling customers to push images that have been built outside of the `docker build` command

feat: added push-image command

---

.circleci/test-deploy.yml
src/scripts/docker-buildx.sh

This `PR` adds the capability to push multi-architecture images for public registries n `aws ecr`.  There has been a previous fix in PR #235 that changes the `uri` of the public registry schema to use an assigned `registry-alias`. This enabled pushing multi-architecture images to public registries using the `docker buildx build` command.

feat: push multi-architecture images to public registries

---

src/scripts/docker-buildx.sh
src/scripts/ecr-login.sh
src/scripts/push-image.sh

This `PR` adds validation for the required `registry-id` parameter with an `env_var` type. 
If a user does not add one in CircleCI, the job fails with an `exit 1`

feat: add validation for registry id

---

src/commands/build-image.yml
src/scripts/docker-buildx.sh

This `PR` evaluates the `extra-build-args` parameter. Now users are able to use expressions containing sub shells like `--build-arg VERSION=$(cat version.txt)` will be properly evaluated.

fix: evaluated extra build arg parameter

---

src/jobs/build-and-push-image.yml

This `PR` adds the `checkout` parameter to the ` build-and-push` job

fix: add checkout parameter to build-and-push job

---

sample/repo-policy.json
src/commands/build-and-push-image.yml
src/commands/set-repo-policy.yml
src/examples/simple-build-and-push.yml
src/jobs/build-and-push-image.yml
src/scripts/set-repo-policy.sh

This builds on the with the existing `create-repo` parameter by allowing a user to also set an ECR repository policy.  This solves situations where AWS multi-account access is required and must be set outside of this orb before the repository is fully functional.
Adds a new boolean `set-repo-policy` and a new script `set-repo-policy.sh` calling [aws ecr set-repository-policy ](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ecr/set-repository-policy.html).

feat: Add set-repository-permissions

---

.circleci/test-deploy.yml
src/commands/build-and-push-image.yml
src/commands/build-image.yml
src/scripts/docker-buildx.sh

This `PR` adds the `build-path` parameter to the `docker-build-and-push-image` command and job along with the `build-image` command. 
This enables users to specify the path of the build directory in the case that it differs from the path to the `Dockerfile`.

feat: add build-path parameter

---

.circleci/test-deploy.yml
src/scripts/docker-buildx.sh

This `PR` separates the expansion of the `extra-build-args` from the `$@` array and expands with `${ORB_EVAL_EXTRA_BUILD_ARGS:+$ORB_EVAL_EXTRA_BUILD_ARGS}` at runtime.

fix: extra-build-args expansion

---

.circleci/config.yml
.circleci/test-deploy.yml
src/@orb.yml
src/commands/build-and-push-image.yml
src/commands/build-image.yml
src/commands/create-repo.yml
src/commands/ecr-login.yml
src/commands/push-image.yml
src/commands/set-repo-policy.yml
src/examples/simple-build-and-push.yml
src/jobs/build-and-push-image.yml

This `PR` adds the `auth` parameter to the `build-and-push` job, requiring users to customize their authentication method by importing the `aws-cli` orb and using the `aws-cli/setup` command to authenticate using static AWS keys or a valid `role-arn` for OIDC.

feat!/auth-step-parameter

---

src/jobs/build_and_push_image.yml

This `PR` adds the missing `build-path` parameter to the `build-and-push-image` job.

fix: add missing build-path parameter to job

---

src/scripts/ecr_login.sh

Currently, when a user runs the `aws-ecr/ecr_login` command successfully, a session token is generated and stored in the `~/.docker/config.json` file. However, this token is only valid for 12 hours. Some customers' build processes take longer than 12 hours. This causes subsequent steps to fail with the following error:
`ERROR: denied: Your authorization token has expired. Reauthenticate and try again.`
When trying to run the `aws-ecr/ecr_login` command again to log in, the build fails because it tries to use the existing token in `~/.docker/config.json` that's already expired. 
To solve this, I've added the `docker logout` command before running the `aws ecr login` command. The `docker logout` command automatically deletes any existing session token in `~/.docker/config.json`. This …

fix: add docker logout command to clear expired token

---

.circleci/test-deploy.yml
src/scripts/docker_buildx.sh

Due to a limitation with `docker buildx` found [here](https://github.com/docker/buildx/issues/59#issuecomment-616061869), users get the following error when trying to build an image with multiple platforms without pushing it: 
```
error: docker exporter does not currently support exporting manifest lists
``` 
Currently, when a user sets the `push_image` parameter to `false`, the `--load` flag is automatically applied to the `docker buildx` command. 
The `--load` flag is a shorthand for the combination of `--output=type=docker` and `--push=false` flags. It it instructs Docker Buildx to build the image and store it directly in the local Docker daemon without pushing it to a registry. This allows users to use the image immediately on their local machine without the need to push it to a …

fix: remove load with multi-platform

---

.circleci/test-deploy.yml
src/commands/tag_image.yml
src/scripts/docker_buildx.sh
src/scripts/tag_image.sh

In the `aws-ecr/tag_image` command, the command fails when a user tries to tag an image with an existing tag. 
This is especially problematic for users who need to rerun failed builds due to network issues. Since the image has already been tagged, rerunning builds will cause failures. 
This `PR` adds the `skip_when_tags_exists` parameter to the `aws-ecr/tag_image` command. When set to `true`, the command will check an image's existing tags and only apply the specified tag is it doesn't exist.

feat: tag command skip when tags exist

---

.circleci/test-deploy.yml
sample/Dockerfile
src/examples/build_test_then_push_image.yml
src/scripts/docker_buildx.sh

Currently, with `docker buildx`, users would like to build an image and test it before pushing it. With the `build_and_push_image` command, this is not obvious. 
This `PR` adds a test to `test-deploy.yml` and a usage example that shows users how do achieve this scenario.

test: create test for building testing and pushing image

---

.circleci/test-deploy.yml
src/scripts/docker_buildx.sh

When a user runs the `build_and_push_image` job with one specified platform in a `cimg` executor, the default docker `builder` is used. This is problematic because without using the `docker buildx builder`, some features like the `--cache-to` flag will not work. 
This `PR` checks the current `builder` using the `docker buildx inspect` command. If the `builder` is the `default`, `docker buildx create --use` will be run to set up a new builder to be used.

fix: --cache-to flag not working 

---

src/commands/build_and_push_image.yml
src/commands/build_image.yml
src/commands/ecr_login.yml
src/commands/push_image.yml
src/examples/simple_build_and_push.yml
src/jobs/build_and_push_image.yml
src/scripts/docker_buildx.sh
src/scripts/ecr_login.sh
src/scripts/push_image.sh

This `PR` renames the `registry_id` parameter to `account_id`, matching the `AWS` Documentation. 
It also changes the `type` of this parameter from `env_var_name` to `string` with the `default` value of `${AWS_ACCOUNT_ID}`

refactor!: rename registry_id and change type

---

.circleci/test-deploy.yml
src/scripts/docker_buildx.sh

This pull request fixes the expansion of the `extra_build_args` parameter. Users have reported that  having multiple flags causes the entire string to be wrapped in single quotes, making jobs fail.

fix: extra build arg expansion

---

src/scripts/docker_buildx.sh

Fix for https://github.com/CircleCI-Public/aws-ecr-orb/issues/311
Specify profile name when calling aws ecr put-lifecycle-policy.

fix: set profile when calling aws ecr put-lifecycle-policy (#311)

---

src/commands/build_and_push_image.yml
src/commands/build_image.yml
src/commands/create_repo.yml
src/commands/ecr_login.yml
src/commands/push_image.yml
src/commands/set_repo_policy.yml
src/commands/tag_image.yml
src/jobs/build_and_push_image.yml

Fixes the commands & jobs' descriptions re: AWS CLI installations.
As of v9.x, the commands & jobs do not explicitly install AWS CLI by default.
Rather, it is assumed that the executor chosen would have the AWS CLI already installed. 
For instance, the `aws-ecr/default` executor is the `ubuntu-2004:2022.04.2` Machine executor, which comes pre-installed with AWS CLI.
I understand that alternatively, users can ensure the AWS CLI is installed via:
1)  as part of the `auth` parameter's steps when using the build_and_push_image job, or
2) adding AWS installation steps as [`pre-steps` if needed](https://circleci.com/docs/reusing-config/#using-pre-and-post-steps)

docs: rm description re: AWS CLI installations

---

.circleci/test-deploy.yml
src/commands/build_image.yml
src/commands/create_repo.yml
src/commands/ecr_login.yml
src/commands/push_image.yml
src/commands/set_repo_policy.yml
src/commands/tag_image.yml
src/scripts/create_repo.sh
src/scripts/docker_buildx.sh
src/scripts/ecr_login.sh
src/scripts/push_image.sh
src/scripts/set_repo_policy.sh
src/scripts/tag_image.sh

Version `9.0.0` of this orb replaced `eval` with `cicleci env subst`. 
This had unintended consequences like: 
- expanding variables containing sub-shells
- string operations (ie `${CIRCLE_SHA1:0:7}`)
This PR reverts back to using `eval` for variable expansion. 
**PLEASE NOTE: We will be reintroducing `circleci env subst` again in a later major release** but just wanted to make this change to include bug fixes for folks using older versions of the orb.

refactor: revert to eval

---

src/scripts/docker_buildx.sh

This pull request fixes an issue with checking for the current context being used with `docker buildx`.
It switches the `docker buildx inspect` command to `docker buildx ls`, which will correctly check to see if the default context is being used.

fix: switch buildx command to fix validation

---

src/commands/build_and_push_image.yml
src/commands/build_image.yml
src/jobs/build_and_push_image.yml

This PR updates the description for the `extra_build_args` parameter. For users that want to use multi line arguments, they need to use `>-` instead of `|` like below: 
```
extra_build_args: >-
--build-arg ARG1=<< parameters.arg1 >>
--build-arg ARG2=<< parameters.arg2 >>
--build-arg ARG3=<< parameters.arg3 >>
```

docs: update desciptions to include multi line arguments

---

.circleci/test-deploy.yml
src/commands/ecr_login.yml
src/scripts/ecr_login.sh
src/scripts/utils.sh

This pull request installs the `aws ecr credential helper` and uses it to log into `ECR`.
It replaces the standard login and removes this warning:
```
WARNING! Your password will be stored unencrypted in /home/circleci/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
```

feat: aws ecr credential helper

---

src/scripts/ecr_login.sh

Fixes #333 
The change is needed to update the `${HOME}/.docker/config.json` file to with multiple ECR entries. The `jq` command currently fails when attempting to add a second ECR entry.
Removes double quotes around the `$jq_flag` so that it is properly handled when it is empty. With the double quotes, the `jq` command is interpreting the empty string as a parameter and then failing to find the config file because of how it is parsing the flags. 
I also fix the indentation of the `jq` command so that the staring matches the level of the `if` statement above it and indent the additional parts of the `jq` command a couple extra spaces.

fix: fix jq command when working with an existing Docker config.json file

---

.circleci/test-deploy.yml
src/scripts/ecr_login.sh

Users have pointed out that, for various reasons, it is unnecessary to install the `amazon-ecr-credential-helper` every time and that we should instead check first if it is already installed.
This PR picks up from the work done in #348. Thank you @ryandgood  
- Check if `amazon-ecr-credential-helper` is already installed before attempting to download and install.

Only install ecr-credential-helper when not already installed

---

.circleci/test-deploy.yml
src/scripts/docker_buildx.sh

As mentioned in #351 the build_and_push_image breaks when specifying multiple platforms and trying to pull.
This wasn't identified as the test for this situation was not passing multiple platforms, so I'm adding that.
I'm also adding a pull for all the platforms specified to fix the issue.

Update pull behavior and add platform to test

---

.circleci/test-deploy.yml
src/scripts/ecr_login.sh

The tests were using an old version of the aws-cli that has a differente behavior when using OIDC authentication, I'm updating it to the newest.
Also refactoring the strucutre of the tests.
As mentioned in #352, the installation of credentials helper might ask for confirmation in environments with missing packages making the workflow fail, I'm adding the -y flag to the install command to avoid this.

Updates to use new version of aws cli

---

src/jobs/build_and_push_image.yml

#342  describes an issue with the description of the PATH parameter in build_and_push_image job. This parameter is used to pass Dockerfile location only, and is not intended to overwrite or be overwritten. The BUILD_PATH parameter is used to pass the context location only, and is not intended for overwriting either.
I'm updating the description to make this more clear, as the command with the same name.

Update path description on job

---

src/examples/build_and_push_image_w_registry_login.yml
src/examples/build_test_then_push_image.yml

The example in the CircleCI registry doesn't show the contents of the workflow: https://circleci.com/developer/orbs/orb/circleci/aws-ecr#usage-build_and_push_image_w_registry_login
Indent example YAML properly

Fix example content missing on CircleCI

---

.circleci/test-deploy.yml
src/executors/default.yml
src/scripts/docker_buildx.sh

I'm adding a new way to parse the extra args to the build script, so the parameters with spaces don't have errors.
This is similar to the implementation done in docker-orb, and also requires the = when using spaces to avoid problems.

Fix issue with spaces on extra_build_args

---

src/scripts/tag_image.sh

My CI AWS profile is given an aws managed policy which does not have `ecr:ListImages` permission. [EC2InstanceProfileForImageBuilderECRContainerBuilds](https://docs.aws.amazon.com/aws-managed-policy/latest/reference/EC2InstanceProfileForImageBuilderECRContainerBuilds.html) 
The `tag_image` command has a flag to `skip_when_tags_exist` (default false). When the flag is not set, there is no use for the `ListImages` output.

Only list images when their use case is not skipped

---

src/scripts/docker_buildx.sh

Fixes #387
Do not create a new builder when it already exists with the same name,
which solves a potential issue when running `build_image` multiple times.

fix: do not recreate builder if exists

---

src/scripts/docker_buildx.sh

Regression added in #388, the following error is obtained:
```
ERROR: Multi-platform build is not supported for the docker driver.
```
When the builder exists and we skip creating it, we're missing the step to set it as current

fix: set builder when it exists
