CircleCI-Public/aws-ecr-orb

- .circleci/config.yml
- .yamllint
- Dockerfile
- README.md
- src/@orb.yml
- add automated deployment
- fix ECR login
- add option to create repo if it doesn't exist
- add integration testing (orb builds & pushes, & then deletes, an image)
> Add automation

- .circleci/config.yml
- README.md
- src/@orb.yml
https://github.com/CircleCI-Public/aws-ecr-orb/pull/6
> add extra build args

- .circleci/config.yml
- .github/CODEOWNERS
- .github/PULL_REQUEST_TEMPLATE.md
- src/@orb.yml
- src/commands/build-and-push-image.yml
- src/executors/default.yml
- src/jobs/build-and-push-image.yml
- make `repo` param description consistent across job, command
- refactor config to be more DRY
- use newer orb-tools
- add `setup-remote-docker` param
- update codowners, add PR template
> Fix repo param description

- .circleci/config.yml
- README.md
- src/commands/build-and-push-image.yml
- src/commands/build-image.yml
- src/commands/push-image.yml
- src/examples/simple-build-and-push.yml
- src/jobs/build-and-push-image.yml
https://github.com/CircleCI-Public/aws-ecr-orb/issues/20
Approach as described in the issue. I've changed the default behaviour of the push command to push all images, as keeping a default of "latest" seemed a bit weird - pushing all images also pushes "latest". Let me know if that's acceptable, otherwise I can make it the same default once again
> Support for multiple tags

- src/commands/build-and-push-image.yml
- src/commands/build-image.yml
- src/commands/push-image.yml
- src/jobs/build-and-push-image.yml
Resolves #43 
Fixed typo as described on the issue
> Fix url typo

- README.md
- src/commands/build-and-push-image.yml
Repository created by the orb shall have security scanning enabled by default.
> Add image scanning for created repository

- .circleci/config.yml
- README.md
- src/@orb.yml
The only change to the orb is to add `source_url`.
The other changes in this PR are to update the pipeline to be in line with Orb Starter Kit's, and to update the readme.
> Add source_url and update pipeline [semver:patch]

- .circleci/config.yml
- src/executors/default.yml
This can be useful to users who wish to use DLC.
DLC test: https://app.circleci.com/pipelines/github/CircleCI-Public/aws-ecr-orb/215/workflows/64234ba2-9a78-4223-824f-e572a6f1efd3/jobs/605/parallel-runs/0/steps/0-108
> Add dlc parameter to default executor [semver:patch]

- README.md
- src/commands/build-and-push-image.yml
- src/jobs/build-and-push-image.yml
[docker engine 17 is not supported](https://circleci.com/docs/2.0/building-docker-images/?mkt_tok=eyJpIjoiTnpNek1ETXpNemMzTVRGayIsInQiOiI1dzdMbGlodFF1NTZhU0t0OUsxSXNrb3BwOW8xTjVqSGhJZ29BSmU2WFpUSnlZNUEwT0hcL2xqK0I3WXZQSE82eHNzQVE0bjUrOGJTaGdlME9kRStnXC9MSENEK1NwcCtsb2M1OGlvaXVmSkdJMCtQQ2lpWjhTaWxLOFg3blRUaFlKIn0%3D#docker-version)
> [semver:minor] allow to config the remote docker version

- src/commands/build-and-push-image.yml
- src/commands/create-repo.yml
> [semver:minor] Break create-repo into standalone command.

- README.md
- src/executors/default.yml
I'm trying to optimize the build time of my image and I'd like to be able to tune the `resource_class` parameter to use larger machines.
Adds the `resource-class` configuration option
> [semver:minor] Expose the resource_class config option

- .circleci/test-deploy.yml
- src/commands/ecr-login.yml
- src/jobs/build-and-push-image.yml
As noted in an earlier issue @ #180, I was also unable to utilize the `build-and-push-image` job when setting up with `role-arn` and `new-profile-name` parameters.
Specifically, I was seeing that the `aws ecr ger-login-password` failing due to it [using the `profile-name` rather than `new-profile-name` (which was set up with the supplied role ARN)](https://app.circleci.com/pipelines/github/kelvintaywl-cci/aws-ecr-orb-explore/1/workflows/9fe80e75-b9db-4ae3-9af6-e7e282bc9c12/jobs/2?invite=true#step-105-24).
```
An error occurred (AccessDeniedException) when calling the GetAuthorizationToken operation: User: arn:aws:iam::123456789012:user/kelvin-assume-role-only is not authorized to perform: ecr:GetAuthorizationToken on resource: * because no identity-based policy allows the …
```
> Fix: uses the new profile name when building & pushing images

- .circleci/test-deploy.yml
- sample/Dockerfile
- src/jobs/build-and-push-image.yml
- src/scripts/docker-buildx.sh
Solves https://github.com/CircleCI-Public/aws-ecr-orb/issues/233
Checks if the docker context already exists to avoid a failure when running the command twice in the same job.
> fix: allow multiple runs of the command in the same job

- src/scripts/docker-buildx.sh
file:// is required when passing file path as parameter in AWS CLI.
Fixes #217 .
> Prefix path parameter with file scheme

- src/scripts/ecr-login.sh
Fixes #213 
The `~/.docker/config.json` file will not exist if you have not logged in with ECR beforehand.
This file was being read without checking for the existence of the file, resulting a file does not exist error is displayed.
Check for the existence of the file before reading it in this PR.
> check .docker/config.json existence before reading

- .circleci/test-deploy.yml
- src/commands/build-image.yml
- src/commands/create-repo.yml
- src/commands/ecr-login.yml
- src/commands/set-repo-policy.yml
- src/scripts/create-repo.sh
- src/scripts/docker-buildx.sh
- src/scripts/ecr-login.sh
- src/scripts/push-image.sh
- src/scripts/set-repo-policy.sh
- src/scripts/tag-image.sh
This `PR` replaces `eval` with `circleci env subst`. It also updates all variable names to follow the Orb Standardization Guide.
> refactor: implement circleci env subst

- src/executors/default.yml
> update image to current tag

- src/commands/tag_image.yml
- src/scripts/tag_image.sh
https://github.com/CircleCI-Public/aws-ecr-orb/issues/315
Add AWS profile (`aws_profile`) parameter to `tag_image` command.
> Added AWS profile to tag_image

- src/scripts/docker_buildx.sh
Fix lint failure on publish of the latest PR merge.
Shellcheck ignore an implicitly-used environment variable
> Ignore lint on indirectly used variable

- .circleci/test-deploy.yml
- src/commands/build_and_push_image.yml
- src/commands/ecr_login.yml
- src/jobs/build_and_push_image.yml
- src/scripts/ecr_login.sh
The credentials helper has caused many issues compared to the classic docker login, I'm adding a parameter to decide which option to use in the job and the commands.
> Add parameter to use or not the ecr-credentials-helper

- src/scripts/docker_buildx.sh
> Pass --platform to docker pull when the tag exists

- .circleci/test-deploy.yml
Previously, some steps where deleted from the deployment workflow, I'm re adding them.
> Fix deployment

- src/examples/build_and_push_image_w_registry_login.yml
- src/examples/build_test_then_push_image.yml
- src/examples/simple_build_and_push.yml
> Fix examples

- src/commands/build_and_push_image.yml
- src/commands/create_repo.yml
- src/jobs/build_and_push_image.yml
- src/scripts/create_repo.sh
#374 
Add parameter to configure image tag mutability
> feat: image tag mutability is configurable

- .circleci/test-deploy.yml
- src/commands/build_and_push_image.yml
- src/commands/create_repo.yml
- src/commands/tag_repo.yml
- src/jobs/build_and_push_image.yml
- src/scripts/create_repo.sh
- src/scripts/tag_repo.sh
[#378 ](https://github.com/CircleCI-Public/aws-ecr-orb/issues/378)
Add parameter for tagging ECR repository
> [Feature Request]Add parameter for tagging ECR repo

- src/examples/simple_build_and_push.yml
> Fix typo on example
